"""
Django settings for mssql_demo project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7%bw7*9e@a8-ws8$ageo*8n3z(ql=y+@#!c61u-=u)q@d3#%&c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
import os
ALLOWED_HOSTS = ['192.168.1.65' , '127.0.0.1', 'localhost']  # Allow all hosts for development; restrict in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'licenses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mssql_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mssql_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'License_db_02-01-2023',
        'USER': 'haroon',
        'PASSWORD': 'haroon111??M',
        'HOST': 'host.docker.internal',  # Windows host SQL Server
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Use 17 since it's on your host
            'Encrypt': 'no',  # Disable encryption for development
            'TrustServerCertificate': 'yes',
            'MultipleActiveResultSets': True,
            'Connection Timeout': 30,
            'Command Timeout': 30,
        },
    },
    'old_lic_data': {
        'ENGINE': 'mssql',
        'NAME': 'OldLicData',
        'USER': 'haroon',
        'PASSWORD': 'haroon111??M',
        'HOST': 'host.docker.internal',  # Windows host SQL Server
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Use 17 since it's on your host
            'Encrypt': 'no',  # Disable encryption for development
            'TrustServerCertificate': 'yes',
            'MultipleActiveResultSets': True,
            'Connection Timeout': 30,
            'Command Timeout': 30,
        },
    },
}




# For MSSQL specific settings
# No need to manually patch DatabaseWrapper.data_types for DateTimeField.
# Django and django-mssql-backend handle DateTimeField mapping automatically.
# If you encounter issues, set the correct driver and options in DATABASES['OPTIONS'].

DATABASE_ROUTERS = ['licenses.db_router.LicenseRouter']

# DATABASE_ROUTERS = ['licenses.db_routers.LicenseRouter']
# DATABASE_ROUTERS = ['licenses.db_routers.LicenseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'licenses:search'  # Using the app namespace
LOGIN_URL = '/'

LOGOUT_REDIRECT_URL = 'licenses:login'  # Using the app namespace