# Generated by Django 5.0.14 on 2025-07-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abcchk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=50)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=500)),
                ('fathername', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FatherName', max_length=500)),
                ('learnerno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LearnerNo', max_length=50)),
                ('issuedate', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IssueDate', max_length=50)),
                ('expirydate', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ExpiryDate', max_length=50)),
                ('vehicletype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VehicleType', max_length=250)),
                ('address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=1000)),
                ('cnic', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNIC', max_length=50)),
                ('userid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserID', max_length=50)),
                ('comments', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comments', max_length=1000)),
                ('changedate', models.DateTimeField(db_column='ChangeDate')),
            ],
            options={
                'db_table': 'ABCChk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dialogbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=50)),
                ('endo_issue', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Endo_Issue', max_length=250)),
                ('vehicletype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VehicleType', max_length=250)),
                ('endo_user', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Endo_User', max_length=250)),
                ('changedate', models.DateTimeField(blank=True, db_column='ChangeDate', null=True)),
            ],
            options={
                'db_table': 'DialogBox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endo',
            fields=[
                ('serialno', models.BigAutoField(db_column='SerialNo', primary_key=True, serialize=False)),
                ('licenseno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=50, null=True)),
                ('endo_user', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('endo_user1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('vehicletype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VehicleType', max_length=255, null=True)),
                ('endo_issue', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('endo_exp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'endo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endorsenumber',
            fields=[
                ('serialno', models.BigAutoField(db_column='SerialNo', primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(blank=True, db_column='Number', null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'EndorseNumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('serialno', models.BigAutoField(db_column='SerialNo', primary_key=True, serialize=False)),
                ('computerno', models.BigIntegerField(blank=True, db_column='ComputerNo', null=True)),
                ('licenseno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=20, null=True)),
                ('learnerno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LearnerNo', max_length=50, null=True)),
                ('learnerdate', models.DateTimeField(blank=True, db_column='LearnerDate', null=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=500, null=True)),
                ('fathername', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FatherName', max_length=500, null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('issuedate', models.DateTimeField(blank=True, db_column='IssueDate', null=True)),
                ('expirydate', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
                ('rnewexpirydate', models.DateTimeField(blank=True, db_column='RNewExpiryDate', null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=1000, null=True)),
                ('cnic', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNIC', max_length=100, null=True)),
                ('bloodgroup', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BloodGroup', max_length=50, null=True)),
                ('amount', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Amount', max_length=50, null=True)),
                ('enterby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EnterBy', max_length=50, null=True)),
                ('enteron', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EnterOn', max_length=50, null=True)),
                ('isprint', models.SmallIntegerField(blank=True, db_column='IsPrint', null=True)),
                ('islpc', models.SmallIntegerField(blank=True, db_column='IsLPC', null=True)),
                ('isoldlp', models.SmallIntegerField(blank=True, db_column='IsOldLP', null=True)),
                ('isndl', models.SmallIntegerField(blank=True, db_column='IsNDL', null=True)),
                ('mobileno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MobileNo', max_length=50, null=True)),
                ('owner', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Owner', max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Relationship', max_length=50, null=True)),
                ('verified', models.SmallIntegerField(blank=True, db_column='Verified', null=True)),
                ('verifiedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VerifiedBy', max_length=50, null=True)),
                ('verifieddate', models.DateTimeField(blank=True, db_column='VerifiedDate', null=True)),
                ('enable', models.SmallIntegerField(blank=True, db_column='Enable', null=True)),
            ],
            options={
                'db_table': 'License',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenseupdation',
            fields=[
                ('serialno', models.BigAutoField(db_column='SerialNo', primary_key=True, serialize=False)),
                ('computerno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ComputerNo', max_length=10)),
                ('number', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Number', max_length=50)),
                ('updationtypeno', models.BigIntegerField(db_column='UpdationTypeNo')),
                ('preexpiry', models.DateTimeField(db_column='PreExpiry')),
                ('newissuedate', models.DateTimeField(db_column='NewIssueDate')),
                ('newexpirydate', models.DateTimeField(db_column='NewExpiryDate')),
                ('amountpaid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AmountPaid', max_length=10)),
                ('enterby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EnterBy', max_length=50)),
                ('enteron', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EnterOn', max_length=50)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=10)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LicenseUpdation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licensevehicle',
            fields=[
                ('licenseno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=20, primary_key=True, serialize=False)),
                ('vehicletypeid', models.IntegerField(db_column='VehicleTypeID')),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'LicenseVehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldLicense',
            fields=[
                ('serialno', models.BigAutoField(db_column='SerialNo', primary_key=True, serialize=False)),
                ('computerno', models.BigIntegerField(blank=True, db_column='ComputerNo', null=True)),
                ('licenseno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LicenseNo', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=250, null=True)),
                ('fathername', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FatherName', max_length=250, null=True)),
                ('dob', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DOB', max_length=50, null=True)),
                ('learnerno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LearnerNo', max_length=250, null=True)),
                ('learnerdate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LearnerDate', max_length=50, null=True)),
                ('issuedate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IssueDate', max_length=50, null=True)),
                ('expirydate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ExpiryDate', max_length=50, null=True)),
                ('vehicletype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VehicleType', max_length=250, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=1000, null=True)),
                ('cnic', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNIC', max_length=50, null=True)),
                ('bloodgroup', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BloodGroup', max_length=50, null=True)),
                ('amount', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Amount', max_length=50, null=True)),
                ('version', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Version', max_length=50, null=True)),
                ('userid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserID', max_length=50, null=True)),
                ('comments', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comments', max_length=1000, null=True)),
                ('verifieddate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VerifiedDate', max_length=50, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('verifiedby', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VerifiedBy', max_length=250, null=True)),
                ('blocked', models.SmallIntegerField(blank=True, db_column='Blocked', null=True)),
            ],
            options={
                'db_table': 'Old_License',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updationtypeno', models.BigIntegerField(db_column='UpdationTypeNo')),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=100)),
            ],
            options={
                'db_table': 'UpdationType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleno', models.BigIntegerField(db_column='VehicleNo', primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=100)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicletype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicletypeid', models.IntegerField(blank=True, db_column='VehicleTypeID', null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'VehicleType',
                'managed': False,
            },
        ),
    ]
