# Generated by Django 5.0.14 on 2025-07-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abcchk',
        ),
    ]
