# Generated by Django 5.0.14 on 2025-07-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_delete_abcchk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogbox',
            options={},
        ),
        migrations.AlterModelOptions(
            name='endo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oldlicense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
