# Generated by Django 5.0.14 on 2025-08-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_dialogbox_options_alter_endo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldlicense',
            name='bloodgroup',
        ),
    ]
